version: '3.8'

services:

  pg1:
    image: postgres
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    ports:
      - "6666:5432"
    networks:
      - network1

  node1:
    build:
      context: .
      target: $NODE_DOCKER_BUILD_TARGET
    environment:
      - NODE_ENV
      - DB_HOST
      - DB_PORT
      - DB_USERNAME
      - DB_PASSWORD
      - DB_NAME
    ports:
      - "3333:3000"
    networks:
      - network1
    volumes:
      - ./src:/opt/node/src
      - ./node_modules:/opt/node/node_modules
      - ./package.json:/opt/node/package.json
      - ./package-lock.json:/opt/node/package-lock.json
      - ./tsconfig.json:/opt/node/tsconfig.json
    depends_on:
      - pg1

networks:
  network1:
